name: test

on:
  push:
    branches:
      - develop
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: test
      uses: jwyxym/jwyxym/shadowsocks@develop
      with:
          ss_server: ${{ secrets.SS_SERVER }}
          ss_server_port: ${{ secrets.SS_SERVER_PORT }}
          ss_pass: ${{ secrets.SS_PASS }}